def app
pipeline {
    agent any
    environment {
        ENV_TYPE = "production"
        PORT = 3001
        NAMESPACE = "picboard-space"
        REGISTRY_HOSTNAME = "itinc"
        PROJECT = "users-microservice"
        SERVICE="users-microservice"
        REGISTRY = "registry.hub.docker.com"
        DEPLOYMENT_NAME = "users-microservice-deployment"
        IMAGE_NAME = "${env.BUILD_ID}_${env.ENV_TYPE}_${env.GIT_COMMIT}"
        DOCKER_BUILD_NAME = "${env.REGISTRY_HOSTNAME}/${env.PROJECT}:${env.IMAGE_NAME}"
    }

    stages {
        stage('Clone repository') {
            steps {
                checkout scm
            }
        }
        stage('Unit tests') {
            steps {
                script {
                    sh '''
                       export NVM_DIR="$HOME/.nvm"
                       [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
                       nvm install --lts
                       nvm use --lts
                       yarn install
                       DATABASE_DIRECT_URL="postgresql://neondb_owner:npg_GoacVwi4b7dy@ep-broad-shadow-alxx727o.c-3.eu-central-1.aws.neon.tech/users_db?sslmode=require&channel_binding=require" yarn run prisma:generate:users:jenkins
                       yarn test
                    '''
                }
            }
        }
        stage('e2e tests') {
            steps {
                script {
                    sh '''
                       export NVM_DIR="$HOME/.nvm"
                       [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
                       nvm use --lts
                       yarn test:users:e2e
                    '''
                }
            }
        }
        stage('Build docker image') {
            steps {
                echo "Build image started..."
                    script {
                       app = docker.build("${env.DOCKER_BUILD_NAME}", "--build-arg service=${env.SERVICE} --build-arg port=${env.PORT} -f ./apps/${env.SERVICE}/Dockerfile ./")
                    }
                echo "Build image finished..."
            }
        }
        stage('Push docker image') {
             steps {
                 echo "Push image started..."
                     script {
                        docker.withRegistry("https://${env.REGISTRY}", 'picboard-space') {
                            app.push("${env.IMAGE_NAME}")
                        }
                     }
                 echo "Push image finished..."
             }
       }
       stage('Delete image local') {
             steps {
                 script {
                    sh "docker rmi -f ${env.DOCKER_BUILD_NAME}"
                 }
             }
        }
        stage('Preparing deployment') {
             steps {
                 echo "Preparing started..."
                     sh 'ls -ltr'
                     sh 'pwd'
                     sh "chmod +x ./apps/${env.SERVICE}/preparingDeploy.sh"
                     sh "./apps/${env.SERVICE}/preparingDeploy.sh ${env.REGISTRY_HOSTNAME} ${env.PROJECT} ${env.IMAGE_NAME} ${env.DEPLOYMENT_NAME} ${env.PORT} ${env.NAMESPACE}"
                     sh "cat ./apps/${env.SERVICE}/deployment.yaml"
             }
        }
        stage('Deploy to Kubernetes') {
             steps {
                 withKubeConfig([credentialsId: 'prod-kubernetes']) {
                    sh "kubectl apply -f ./apps/${env.SERVICE}/deployment.yaml"
                    sh "kubectl rollout status deployment/${env.DEPLOYMENT_NAME} --namespace=${env.NAMESPACE}"
                    sh "kubectl get services -o wide"
                 }
             }
        }
    }
}
